name: Go
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
    
    services:
      redis:
        image: redis
        ports:
        - 6379:6379

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download
        go mod vendor

    - name: test
      run: go test -v ./...
      env:
        REDIS_URL: redis://redis:${{ job.services.redis.ports[6379] }}
